feature/dashboard/UI
splitscale/streamline-pos pull request #17
Opened 2023-11-20 13:50 UTC by ClydeTeia

Overview / Description

## Changes
- added ui for dashboard
- improve margin on dashboard transactions

## Screenshots
(prefer animated gif)

## Checklist
- [ ] Automated tests
- [ yes] Checked on iOS
- [yes ] Checked on Android

Fixes #xx

2023-11-20 14:46 UTC, chdean-09 approved these changes

2023-11-20 17:03 UTC, kasutu requested changes

2023-11-20 17:03 UTC, kasutu commented on src/pages/mobile.tsx
pull anay from master and saylo lang ni sa component

2023-11-21 00:18 UTC, kasutu approved these changes

2023-11-21 00:18 UTC, merged